version: "3"
services:
  docker-ci:
    container_name: docker-ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    build: .
    tty: true
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - "web"

networks:
  web:
    external: true
