version: "3"

services:
  docker-ci:
    container_name: docker-ci
    # image: docker.pkg.github.com/garage-isep/garagebot/garage-bot:main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    ports:
      - "5050:80"
    environment:
      - PORT=80
      - NODE_ENV=production
    env_file:
      app.env