version: "3"

services:
  docker-ci:
    container_name: docker-ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    ports:
      - 5050:8080
    environment:
      - PORT=8080
      - NODE_ENV=production
    env_file:
      app.env